name: "Building and Publishing"

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  ARTEFACT_NAME: taco-cloud
  JAR_PATH: build/libs
  JAR_FILE: taco-cloud.jar

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'azul'
        cache: gradle
    - name: Gradle Assemble
      run: ./gradlew clean assemble
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTEFACT_NAME }}
        path: ${{ env.JAR_PATH }}/${{ env.JAR_FILE }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTEFACT_NAME }}
          path: ${{ env.JAR_PATH }}
      - name: Docker Build and Push
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: aspankov/taco-cloud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "0.0.3,latest"

  repository:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/0.0.3",
              sha: context.sha
            })